### ISSUE TITLE
Spell check in code blocks

### ISSUE THREAD

**Issue by eohomegrownapps** [remnoteio/remnote-issues#1101]
It would be nice if code blocks did not display spell check (e.g. via setting `spellcheck="false"` in the HTML element)

**Comment by hannesfrank** [comment]
I agree. For code blocks it should be off all the time I think and for other content there should be a setting on the desktop app (chrome has this builtin) to turn it off since and/or specify the language: https://www.electronjs.org/docs/tutorial/spellchecker

--- 

Workaround: Use a User Script

Disable spellcheck in `#code-node`s:
```js
window.remnoteDisableSpellcheck = setInterval(() => {
  for (const el of document.querySelectorAll('#code-node'))
    el.spellcheck = "false";
}, 500);
```

Before:
  
![image](https://user-images.githubusercontent.com/4137110/113834448-24e27000-978b-11eb-80a3-b450b6e85aa3.png)

After:

![image](https://user-images.githubusercontent.com/4137110/113834867-9b7f6d80-978b-11eb-9c63-b4de6ab81b42.png)

Disable spellcheck everywhere:
```js
window.remnoteDisableSpellcheck = setInterval(() => {
  for (const el of document.getElementsByClassName('EditorContainer'))
    el.spellcheck = "false";
}, 500);
```

**Comment by drkvj** [comment]
Kindly port this into a feature request on the forum so that other users may be able to vote on it as well. Thank you!

**Comment by hannesfrank** [comment]
https://forum.remnote.io/t/disable-spellcheck-in-code-blocks/3997

**Comment by ecybiss** [comment]
> ```js
> window.remnoteDisableSpellcheck = setInterval(() => {
>   for (const el of document.querySelectorAll('#code-node'))
>     el.spellcheck = "false";
> }, 500);
> ```

Thanks! 
However this tiny block doesn't work in my RN 1.3.6 . Is there anything wrong?
![11111](https://user-images.githubusercontent.com/79266776/114721361-6ebeed80-9d6b-11eb-9a09-2d623455358b.png)

**Comment by emil-ho** [comment]
How do I create a user script, which disables spell checking on the remnote desktop app?
