### ISSUE TITLE
Tag Powerup not adding new tag if copy & pasted

### ISSUE THREAD

**Issue by edhowe721** [remnoteio/remnote-issues#382]
**Describe the bug**
Tag Powerup is on via experimental settings option. New tags get added properly to Tag Powerup when typing out "##tag" one letter at a time, but if I copy "##tag" (i.e. from somewhere outside of Remnote like Word), and paste into Remnote, it does not get added to the Tag Powerup, even though it is a newly tagged rem.

**To Reproduce**
1. Type ##tag anywhere outside of remnote and copy it
2. Open second pane with Tag Powerup and note how many tags are currently used
3. Paste onto a rem in remnote and note that the Tag Powerup number did not increase

**Expected behavior**
Any new tagged rem is added to Tag Powerup, even if copy and pasted 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by drkvj** [comment]
Thanks for submitting this, and apologies for not responding sooner, we are now cleaning up all the reports, to make sure this can be an efficient process from now.

Kindly submit this as a feature request on the forum, so that other users can also vote and give us an idea about the user base interest.
