### ISSUE TITLE
The RTL Document Menu Appears Below The Text

### ISSUE THREAD

**Issue by mfranzs** [remnoteio/remnote-issues#449]
"The options in the menu cannot be accessed"

Screenshot:
![image](https://user-images.githubusercontent.com/953103/103159552-df300780-4798-11eb-8dee-5fe57909b043.png)

**Comment by binabdilwali** [comment]
I am having the same problem

**Comment by binabdilwali** [comment]
the same sort of problem happens when you try to show hidden pieces of text. But it only seems to happen when it is under a rem with Heading Power Up for some reason

As you can see it only disappears under the rem which has the Heading power up.

<img width="814" alt="Screen Shot 2020-12-29 at 9 42 22 AM" src="https://user-images.githubusercontent.com/44670449/103263983-63ada080-49ba-11eb-9588-244ed81ad53f.png">


<img width="811" alt="Screen Shot 2020-12-29 at 9 41 22 AM" src="https://user-images.githubusercontent.com/44670449/103263986-64463700-49ba-11eb-863b-011098edc8f8.png">

**Comment by mfranzs** [comment]
Thanks for the report. We've reproduced this and have deployed a fix. Please let us know if you're still having any problems.
