### ISSUE TITLE
Spaced Repetition system isn't working properly.

### ISSUE THREAD

**Issue by Dovydas0927** [remnoteio/remnote-issues#457]
**Describe the bug**
Spaced Repetition system isn't working properly.

**To Reproduce**
1. Go to 'queue'
2. Click on 'show answer'
3. See error

**Expected behavior**
Seeing full spaced repetition buttons (immediately, 24 hours, 2 days, 7 days)[You got the idea..?]

**Screenshots**
![image](https://user-images.githubusercontent.com/63964560/103212208-e844e400-4912-11eb-8d5b-b5e93bb8ed18.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome, brave]
 - Version [e.g. latest]

**Comment by mfranzs** [comment]
Thanks for reaching out. Is this the first time you've interacted with this card? For the first response, there are only 2 spacing intervals offered. However, your response is also taken into account on further interactions. (Ex. if you press the 4th button instead of the 3rd button, the next spacing intervals presented will be longer because the system understands you know the card better
.)

**Comment by Dovydas0927** [comment]
Thx 👍 I didn't know about it :))
