### ISSUE TITLE
RemNote on macOS (Big Sur) launching with blank screen

### ISSUE THREAD

**Issue by luke-nehemedia** [remnoteio/remnote-issues#539]
This morning I opened RemNote and had a message that an update was available. After clicking on it and relaunching, the app shows a blank screen. No controls, no sidebar, no whatsoever, but also no crash. 
It does not change, also not after several minutes waiting.

**To Reproduce**
1. Update to the latest version
2. See blank screen

**Expected behavior**
Well, the same as on the web version. In the web version I am greeted with two notifications, one of the new features and one about product hunt. 

**Screenshots**
<img width="1016" alt="Bildschirmfoto 2021-01-13 um 11 14 49" src="https://user-images.githubusercontent.com/7863273/104438695-93e76880-5590-11eb-84e1-d9f41c843c89.png">

**Desktop (please complete the following information):**
 - OS: macOS 11.1 (20C69)
 - Browser: nA
 - Version: updated to latest (I guess 1.2 BETA)

**Comment by formsandlines** [comment]
Doesn't seem to be Big Sur specific, the exact same issue happened to me on macOS 10.15.6 (Catalina) after I updated the app to the latest version a few minutes ago.

Maybe this open issue is also related: https://github.com/remnoteio/remnote-issues/issues/536 Although for me the window remains blank, even after restarting the app. There is nothing I can do to fix it.

This tweet from a Windows user also seems to be related: https://twitter.com/KerresDaniel/status/1349302387027140609

I hope this can be fixed very soon, since I need to access my local graphs.

**Comment by formsandlines** [comment]
I just downloaded RemNote 1.1.6 from https://www.remnote.io/download and it works – problem solved for me.

**Comment by luke-nehemedia** [comment]
I can confirm the fix from formsandlines:

> I just downloaded RemNote 1.1.6 from https://www.remnote.io/download and it works – problem solved for me.

After re-installing the app, everything seems to be working fine. So probably there was something going wrong during the update.

**Comment by mfranzs** [comment]
Thanks for the update!
