### ISSUE TITLE
Can't earn Credits on Remnote web

### ISSUE THREAD

**Issue by ao-kamal** [remnoteio/remnote-issues#605]
**Describe the bug**
Can't earn Credits on Remnote web

**To Reproduce**
1. Share remote invite link
2. Friend signs up and gets free remnote credits
3. Credits do not show up in my account
4. On logging out and logging back in, I get "Failed to award invite credits" message

**Expected behavior**
I expected to get credits immediately

**Screenshots**
![image](https://user-images.githubusercontent.com/58620889/105549379-290cfe80-5d01-11eb-8343-713e044c4c29.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 87.0.4280.141
 

**Additional context**
I have also not been able to use the Desktop App for around a week, I created a Github [https://github.com/remnoteio/remnote-issues/issues/562](issue) but was told to email support since mine was an account-related issue. I still haven't gotten any reply.

**Comment by mfranzs** [comment]
We've pushed a fix for this issue - are you still experiencing it?

**Comment by ao-kamal** [comment]
Yes I'm still experiencing this issue

**Comment by javierigaciorm** [comment]
Same.
Very frustrating.

**Comment by ao-kamal** [comment]
This issue was never fixed lol

**Comment by pariszhuang** [comment]
Hi there, 
The above issue was not fixed. 

Describe the bug
Can't earn Credits on Remnote web

To Reproduce
Steps to reproduce the behavior:

Share remote invite link
Friend signs up and gets free remnote credits
Credits do not show up in my account
On logging out and logging back in, I get "Failed to award invite credits" message
Expected behavior
I expected to get credits immediately
#605
