### ISSUE TITLE
Clipper show a blank page 

### ISSUE THREAD

**Issue by zxc18874151571** [remnoteio/remnote-issues#633]
**Describe the bug**
Clipper show a blank page as the example below shows

**To Reproduce**
1. Go to RemNote Clipper
2. Click on the Clipper

**Expected behavior**
A blank page shows on the clipper.

**Screenshots**
![image](https://user-images.githubusercontent.com/54632186/105747558-331d4000-5f41-11eb-9e6b-89c44dae183c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] newest

**Comment by mfranzs** [comment]
Thanks for reaching out. 
1. Is this on Chrome on Mac? 
2. Is this on every webpage?

**Comment by zxc18874151571** [comment]
1. Chrome
2. Yes. Btw, it does clip the webpage though. Just showing me this blank page.

**Comment by mfranzs** [comment]
Thanks. Do you have any extensions that could be restricting access here? I can't reproduce this and it's loading for other users.

**Comment by zxc18874151571** [comment]
I’m not sure about which one could be the case. But it appears to be working again.

Best regards,
Feiyin Wang

**Comment by mfranzs** [comment]
Great! Let me know if it stops working please.

**Comment by coreygo** [comment]
One potential root cause is blocking of third-party cookies which causes issues with `localStorage`, this leads to an uncaught err in `remoteInject.js`.

Improved error handling and/or additional documentation might be helpful.

Possible workaround:
![Screen_Shot_2022-03-07_at_8_16_14_PM](https://user-images.githubusercontent.com/649879/157165341-ab4434f4-99de-46e8-8dbf-e30e336921de.png)
