### ISSUE TITLE
🔴 the scheduler is not working 🔴

### ISSUE THREAD

**Issue by drstrangez0** [remnoteio/remnote-issues#695]
the scheduler is not working its the **fifth day** with the same problem
whatever I press  the interval will be 24 hours and **am using the normal queue not practice all** 
all my cards are behaving the same and the next image is an example of a card **appeared in 4 days in a row although I answered correctly** 

### The Bug and its cause 
- if you practice a rem **you must wait a full 24 hours till you can practice it again otherwise will considerd as "practice all rem" option** 
- for example, **the upper part of the image below was taken at 9 Am (not full 24 hours from the final practice)** it shows that the **interval is 24 hours(not correct) ...**
- the **lower part of the image was taken at 12:30 pm (a full 24 hours from the last practice)** and It shows the **correct interval** 

![image](https://user-images.githubusercontent.com/70066742/106581904-70db2380-6554-11eb-8586-4dcc05cba6f6.jpg)

### this is due to
- what  @mfranzs said "**due to an upgrade in the scheduler to make it aware of the real world time interval between presses**"
- as a medical student, I create card all the time it does not make sense to wait 24 hours to practice it again 
- Please fix this ASAP because my queue is 700 right now due to the bug 😪

**Comment by hugomarins** [comment]
@drstrangez0 The "Forgot" ratings in the card you showed us made it difficult to me to see if the scheduling is doing as supposed (but your previous isseu showed it very clearly. 

If the analysis you did is correct, it is very strange. For me it makes no sense having to "wait" to review the cards, because the queue is supposed to only show me already due cards. If the card is not due yet (date, not hours; I don't even understand why they record "hours" early/late), it should'nt have been shown, don't you agree? If this card is being shown before the appointed date, this is another problem in the scheduling.

@mfranzs As far as I can see (and in my case solely), the problem is limited to cards that entered learning mode from 30th January or beyound, and the scheduling is normal for cards that entered learning previously.

Learned January 30rd, messed:

![image](https://user-images.githubusercontent.com/54500828/106590765-378ebd80-652c-11eb-8328-997952f629c9.png)

![image](https://user-images.githubusercontent.com/54500828/106590951-715fc400-652c-11eb-9a13-917e2bb8bb42.png)

Learned January 31st, messed:

![image](https://user-images.githubusercontent.com/54500828/106590501-eda5d780-652b-11eb-8f67-da64e28aa9a2.png)

All cards that I learned after Jan 30rd are with messed scheduling (endless 24h loop).

**Comment by drstrangez0** [comment]
@hugomarins the due date is okay but the problem is with the hours must be > 24 hours to practice it again and that's very weird

**Comment by 8888Daniel8888** [comment]
I'm pretty sure here's an underlying bug at play. The very first flashcard I encounter in the queue, even the normal srs one has the ratings 24h 24h immediate immediate even though my scheduler says something else. When I rate that weird flashcard though and click on go back to check the ratings, it's normal again here's a gif of that and pay attention to the four ratings and their intervals![image](https://user-images.githubusercontent.com/69430941/106594616-a4b54980-6552-11eb-8a6f-d4f05605d9de.gif)

It's basically this issue https://github.com/remnoteio/remnote-issues/issues/663 but I found another way to encounter it

**Comment by hugomarins** [comment]
I tried again now and it looks like the eternal loop of 24h scheduling in not occurring anymore. Maybe the team is already correcting the situation. The cards are being scheduled for 3 days Solid and 4 days Easy, as they should. Happy to know!!

**Comment by jyothisable** [comment]
Same issue, not fixed yet
![image](https://user-images.githubusercontent.com/63841734/106701232-5bc1cb80-660c-11eb-9743-c035eea7f71f.png)
