### ISSUE TITLE
Remnote display blank, white screen after upgrade

### ISSUE THREAD

**Issue by smonv** [remnoteio/remnote-issues#910]
**Describe the bug**
After upgrade to the latest version today and reload, Remnote wasn't working anymore. It just displays a blank, white screen all the time. I tried to restart the app and wait more but still blank.

**To Reproduce**
1. Received notification about an upgrade downloaded
2. Click on 'Reload' button on the menu
3. After restart and error happened

**Expected behavior**
Remnote restart and every document display again

**Screenshots**
<img width="1440" alt="Screen Shot 2021-02-28 at 10 42 02" src="https://user-images.githubusercontent.com/8962973/109407348-b0a9f500-79b2-11eb-9c82-4c016f8c322a.png">

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Version 11.2.2

**Comment by mfranzs** [comment]
Thanks for reaching out. Can you please close and re-open to make sure the app is on 1.2.5?

**Comment by smonv** [comment]
> Thanks for reaching out. Can you please close and re-open to make sure the app is on 1.2.5?

I tried it a few times, but no luck still stuck with the blank, white screen.

**Comment by mfranzs** [comment]
Can you try downloading again from https://www.remnote.io/download?

**Comment by efang160** [comment]
I am experiencing this problem as well. I believe the version I have downloaded is 1.2.3. It asks me to 'reload and update' to 1.2.4. After doing that, I am redirected to a blank page as described above.

I hope this piece of information helps and please look into this issue.

**Comment by arunnbabu81** [comment]
@mfranzs i have been using the desktop app on my Mac daily for many hours since the last two months. I haven’t noticed any significant problems with the desktop app till today. 

But today morning, after I closed and opened the desktop app (about two hours back) only a white blank screen is seen.  Nothing else is loading up. It was working fine prior to that. I was on the latest version from the time it was released. 

So I tried using the web app. But custom CSS page in the  web app is showing  “Something went wrong “ message in place of the each of the code blocks (code blocks are not seen, instead this message is seen). This also was not seen till today morning.



After going through this thread, I redownloaded the app and installed it again. Now the issue with desktop and web apps both are not seen. Thanks for correcting it.

**Comment by mfranzs** [comment]
It looks like our MacOS build process was interrupted. It's now finished successfully. Can you please try again now? Many apologies for the inconvenience.

Can you please try:
1) Opening and closing the app
2) Re-downloading from https://www.remnote.io/download if that doesn't work?

**Comment by smonv** [comment]
The app working after re-install, but I'm not sure this issue can be solved with this approach every time. 

This is the second time I got this problem with the upgrade. It quite annoying when you start the day with RemNote, then got problem and have to reinstall the app.
